### ISSUE TITLE
We should add which CORS headers are required

### ISSUE THREAD

**Issue by BigBlueHat** [credential-handler/chapi.io#36]
> We should add which CORS headers are required to help devs.

_Originally posted by @dlongley in https://github.com/credential-handler/chapi.io/pull/35#discussion_r1304774694_

**Comment by dlongley** [comment]
> It is completely safe to augment any resource with `Access-Control-Allow-Origin: *` as long as the resource is not part of an intranet (behind a firewall). In other words, a URL you can fetch from a server on the internet using `wget` or `curl`.

https://annevankesteren.nl/2012/12/cors-101

**Comment by dlongley** [comment]
The above advice must be true for any `manifest.json` file served to enable use of a credential handler.

**Comment by BigBlueHat** [comment]
Then why did they flip the default away from that when the implemented
CORS? Is it truly just for the Intranet use case?

At any rate, happy to know we can just advise that easy change.

**Comment by dlongley** [comment]
> Then why did they flip the default away from that when the implemented CORS?

Browsers won't know whether something is part of an intranet or not -- so the default is to rely entirely on the same origin policy. Therefore, servers must announce that it's ok for browsers to send cross origin requests (and they may can say that those requests can originate from one or more other specific origins -- or come from any other origin `*`).

> At any rate, happy to know we can just advise that easy change.

+1, we should be able to just advise that easy change.
